# -*- coding: utf-8 -*-
"""107062333_hw1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XzPIXptaQBHaoVeBh55TrIL_WgSS3Zhl
"""

import requests
import re
import os
from bs4 import BeautifulSoup

def crawling(mid_add,path_list):
  add_prev ="https://www.blockchain.com/eth/address/"
  add_last = "?view=standard"
  add = add_prev+mid_add+add_last
  r = requests.get(add)
  soup = BeautifulSoup(r.text,'html.parser')
  targets = soup.find_all('div',direction="vertical",class_="sc-1fp9csv-0 koYsLf")

  #print self information
  self_info_title = soup.find_all('span',class_="sc-1ryi78w-0 cILyoi sc-16b9dsl-1 ZwupP sc-1n72lkw-0 ebXUGH")
  self_info_val = soup.find_all('span',class_="sc-1ryi78w-0 cILyoi sc-16b9dsl-1 ZwupP u3ufsr-0 eQTRKC")
  require_inf_val = self_info_val[1:7]
  require_inf_title = self_info_title[1:7]
  for i,j in zip(require_inf_val,require_inf_title):
    print(j.get_text()+":",i.get_text(),file=output)
    #output.write(j.get_text()+": "+i.get_text())

  Price = None
  Date = None
  next_targets = None
  i = 0

  if targets == []:
    return None #沒下筆 直接回傳 NULL

  for target in targets:
    price = target.find_all('span',class_="sc-1ryi78w-0 cILyoi sc-16b9dsl-1 ZwupP u3ufsr-0 eQTRKC sc-85fclk-0 fhjukF",opacity="1")
    date = target.find_all('span',class_="sc-1ryi78w-0 cILyoi sc-16b9dsl-1 ZwupP u3ufsr-0 eQTRKC" ,opacity="1")
    try:
      price[0].get_text()
      date[0].get_text()
      next_targets = target
      Price = price[0].get_text()
      Date = date[0].get_text()
      i+=1
    except:# 正數交易
      #print(i,target)
      i+=1
      continue
  try:
    info_targets_add = next_targets.find_all('a',class_="sc-1r996ns-0 fLwyDF sc-1tbyx6t-1 kCGMTY iklhnl-0 eEewhk",opacity="1")
    next_targets_add = info_targets_add[2].get_text()
  except:
    return None

  print("Date:",Date,file=output)#print date
  #output.write("Date: "+Date)
  print("To:",info_targets_add[2].get_text(),file=output) #print next add
  #output.write("To: "+info_targets_add[2].get_text())
  print("Amount:",Price,file=output)#print price
  #output.write("Amount: "+Price)

  return next_targets_add

output = open("107062333_hw1_output_tmp.txt",'w')
lines = None
with open('ex_input_hw1.txt') as f:
    lines = f.readlines()
for i in lines:
  add = i.replace('\n','')
  path_list = []
  for j in range(4):
    #print(j)
    path_list.append(add)
    add = crawling(add,path_list)
    if add == None or j==3:
      print("--------------------------------------------------------------------------",file=output)
      #output.write("--------------------------------------------------------------------------")
      break
    print("--------------------------------------------------------------------------",file=output)
    #output.write("--------------------------------------------------------------------------")
  cnt = 0
  s = None
  for k in path_list:
    if cnt==0:
      #print(k,end='',file=output)
      s = k
    else:
      #print(" ->",k,end='',file=output)
      s += " -> "+k
    cnt+=1
  print(s,file=output)
  print("--------------------------------------------------------------------------",file=output)
  #output.write("--------------------------------------------------------------------------")
output.close()
output = open("107062333_hw1_output.txt",'w')
filename = open("107062333_hw1_output_tmp.txt",'r',encoding='UTF-8')
for line in filename:
  output.write(line)
os.remove("107062333_hw1_output_tmp.txt")
output.close()